### ISSUE TITLE
issueベースの開発スケジュール

### ISSUE THREAD

**Issue by Saeriina** [Saeriina/mina#21]
■Webアプリの概要
MR（製薬会社の営業）むけの顧客管理アプリ。
営業担当のクリニックを登録し、医師が使用している製品や活動内容を記録することで、効率の良い営業活動につなげるツール。

■1週間辺りの開発に向けられる時間
- 1週間あたり：14時間~18時間

■ProjectsのURL
https://github.com/users/Saeriina/projects/2/views/1?pane=issue&itemId=87627308&issue=Saeriina%7Cmina%7C21

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] トップページ
- [✔] ユーザー登録機能
- [✔ ] ログイン機能
- [✔ ] クリニック一覧
- [✔ ] クリニック登録
- [✔ ] クリニック詳細
- [✔ ] 製品登録
- [✔ ] 製品一覧
- [✔ ] 面会スケジュール作成機能

■MVP後
- [✔ ] 口コミ機能
- [✔ ] クリニック検索機能
- [✔ ] 削除機能
- [✔ ] タスク管理機能
- [✔ ] タスク通知機能
- [✔ ] クリッニク位置情報機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] CI（GitHubActions）
- [ ] ファビコン
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2025年 1月 15日

**Comment by Saeriina** [comment]
- [ ]

**Comment by TakenakaEri** [comment]
提出ありがとうございます！

ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。

細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。

また、忙しい方の場合、大きなストーリーポイントですと、実装に着手するのに時間の確保をしなければいけません。

内容を見ると、もう少し詳細にタスクを分けれそうなので、対応の上、再提出操作をお願いいたします〜！

**Comment by Saeriina** [comment]
追記しました！よろしくお願いします。

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by Saeriina** [comment]
ありがとうございます！
カリキュラムでは「レビュー中」と画面に出てきます！

**Comment by kenchasonakai** [comment]
すみません！
ステータス変更しました 🙇
